### ISSUE TITLE
Minions

### ISSUE THREAD

**Issue by AndreiTS** [McJty/TheOneProbe#165] opened 2017-05-24 16:53 UTC
1.11.2
theoneprobe: 1.4.7

![2017-05-24_13 44 13](https://cloud.githubusercontent.com/assets/13489837/26415287/58ca3c26-4088-11e7-8ed2-e4709c2b13c3.png)

**Comment by McJty** [comment] 2017-05-24 17:01
Check the logs for a crash and report the bug to the author of the mod the entity belongs too. This is probably not a bug in top

**Comment by AtomicStryker** [comment] 2017-05-26 20:25
... that's not how it works. At the very least you need to tell me which method in my Entity you are calling (presumably) and why your mod(!!!) considers the result invalid.

**Comment by tomelfring** [comment] 2017-05-26 21:16
My guess, without any logs/test, is that the warning is coming from (request formatted display name of an entity) :
https://github.com/McJty/TheOneProbe/blob/1.11/src/main/java/mcjty/theoneprobe/apiimpl/providers/DefaultProbeInfoEntityProvider.java#L151

As the mob has the following in its code (returning null as its ITextComponent getDisplayName:

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.11/Minions/src/main/java/atomicstryker/minions/common/entity/EntityMinion.java#L657

**Comment by AtomicStryker** [comment] 2017-05-26 22:11
That's more like it, thank you. Apparently i added this method back in 1.7.10 or earlier for debug purposes (only in my mod), and minecraft happened to add the same prototype in 1.8 onwards. If i was using IDEA or even Netbeans they would have probably warned me about a method override without @Override annotation.

**Comment by McJty** [comment] 2017-05-27 03:27
Sorry about not giving more information but I could not provide the line number you wanted since the original bug report did not contain a crashlog

**Comment by tomelfring** [comment] 2017-05-30 09:00
Can be closed as Minions has updated with a fix

**Closed as completed** 2017-05-30 09:03 UTC
