### ISSUE TITLE
Packet Too big... Looking @ shulker box with... contents.

### ISSUE THREAD

**Issue by spdkils** [McJty/TheOneProbe#226] opened 2018-01-30 15:51 UTC
I removed some contents just to check...

payload may not be larger than 32767
 Just disconnects from the server... Have to toggle off the one probe, then you can look at the box and use it.

No crash log... No message on server...

**Comment by spdkils** [comment] 2018-01-30 16:04
I moved around items, for a good 10 minutes crash after crash... It's not a single item, or a single chest. It's simply if you get too much data inside the chest. No single mod, no single item. Just too much data, poof.

**Comment by josephcsible** [comment] 2018-02-09 00:25
Duplicate of #215

**Closed as completed by josephcsible** 2018-02-09 00:25 UTC
Labels: bug
