### ISSUE TITLE
Odd Character on GUI when playing on server

### ISSUE THREAD

**Issue by TheClaus** [McJty/TheOneProbe#6] opened 2016-06-01 03:56 UTC
I know Direwolf20 mention it in his video about the odd character on the GUI.  I only notice it when playing on a server.  Playing locally it doesn't appear.

Here is the image of it.
![2016-05-31_21 48 25](https://cloud.githubusercontent.com/assets/1347441/15697743/5d491f2e-277a-11e6-8842-8190567b3029.png)

**Comment by McJty** [comment] 2016-06-01 06:54
yes, it is a very weird problem. I cannot reproduce it even when playing on exactly the same server as Direwolf and with exactly the same mods (also same time for that matter). So I have no clue where that character is coming from.

**Comment by McJty** [comment] 2016-06-01 09:58
Will be fixed next release

**Closed by McJty** 2016-06-01 09:58 UTC
