### ISSUE TITLE
[1.16.1] Crash when creating a world with Forge 32.0.68/67

### ISSUE THREAD

**Issue by Tulepeeker** [McJty/TheOneProbe#398] opened 2020-07-17 12:44 UTC
Game crashes when creating a new world while only The One Probe is installed on forge 32.0.68(currently the latest) and 32.0.67. Earlier Forge versions work fine.

[crash-2020-07-17_15.24.38-server.txt](https://github.com/McJtyMods/TheOneProbe/files/4937702/crash-2020-07-17_15.24.38-server.txt)

[crash-2020-07-17_15.41.50-server.txt](https://github.com/McJtyMods/TheOneProbe/files/4937839/crash-2020-07-17_15.41.50-server.txt)

**Comment by McJty** [comment] 2020-07-17 12:48
Probably a change in forge. Forge isn't stable yet. I'll check it out

**Comment by kreezxil** [comment] 2020-07-17 13:50
Issue:  1.16.1-v1 crashes dedicated server Forge 1.16.1 build 32.0.68

Notes:
     NoSuchMethodError caused by Forge changing the command class in build 67

crash report: 
https://gist.github.com/57da643586059260545775c389425d21

fml server latest: 
https://gist.github.com/e6e9f6489b5c3bedd5ec59be0aaa3cf5

**Comment by lehjr** [comment] 2020-07-17 23:30
https://github.com/McJtyMods/TheOneProbe/blob/1.16/src/main/java/mcjty/theoneprobe/ForgeEventHandlers.java#L23

This is broken because the the only thing available from the event now is the server. 
```
ModCommands.register(event.getCommandDispatcher());
```

possible replacement:
```
ModCommands.register(event.getServer().getCommandManager().getDispatcher());
```

**Comment by Edivad99** [comment] 2020-07-18 08:56
#396

**Comment by McJty** [comment] 2020-07-19 14:15
A fix for this has been released

**Closed as completed by McJty** 2020-07-19 14:15 UTC
