### ISSUE TITLE
Rendering issues with entities

### ISSUE THREAD

**Issue by HenryLoenwind** [McJty/TheOneProbe#4] opened 2016-05-31 21:58 UTC
![image](https://cloud.githubusercontent.com/assets/1485873/15691613/208b34ea-278a-11e6-84dd-3706b11987b0.png)

1. entities in the probe display pollute GL state, see JEI on the right side
2. the rotation speed of entities goes up as more of them are displayed
3. the sizes of entities are inconsistent
4. wither skeletons (and other variant mobs) cannot be shown 

![image](https://cloud.githubusercontent.com/assets/1485873/15691736/ceea1fe2-278a-11e6-8f6f-8b79a902e0d0.png)

3. mixing in text gives more corrupted GL state
4. the layout of text beside mob/item doesn't look very good. This may be a "missing documentation how to format it properly" problem?

**Comment by McJty** [comment] 2016-06-01 03:22
Yes, entity display is not completely perfect. I'll see what I can do. About the size that's a bit of a hard problem. I now check the height of the entity and try to estimate how I should scale the entity for that. Do you have a better idea how I could solve that?

I'll check out the GL state corruption

**Comment by HenryLoenwind** [comment] 2016-06-01 05:47
About the size, I'd probably size the display for a 2x3x2 mob, then scale down anything that has a larger dimension to that size and anything that is smaller than 1x1x1 to 1x1x1. That way nothing gets to big and most mobs are rendered in normal proportions to each other.

Something like:

    eb = entity.getEntityBoundingBox();
    scale = 1;
    if (eb.sizeX() > 2 || eb.sizeZ() > 3 || eb.sizeZ() | 2) {
        if (eb.sizeX() > 2)
            scale = 2 / eb.sizeX()
        if (eb.sizeY() > 3)
            scale = min(scale, 3 / eb.sizeY())
        if (eb.sizeZ() > 2)
            scale = min(scale, 2 / eb.sizeZ())
    }
    if (eb.sizeX() < 1 && eb.sizeZ() < 1 && eb.sizeZ() < 1) {
        ....

**Comment by McJty** [comment] 2016-06-01 06:53
Thanks I will try that out. Another thing. Do you happen to know what mob gives that GL state leak because I would like to reproduce it and it seems that for the mobs that I tried it never gives a problem

**Comment by McJty** [comment] 2016-06-07 12:54
The entity render problem should be fixed in next release

**Closed by McJty** 2016-06-07 12:54 UTC
