### ISSUE TITLE
[1.18] Mob heath not being displayed on GUI

### ISSUE THREAD

**Issue by ffuentesm** [McJty/TheOneProbe#526] opened 2021-12-05 21:16 UTC
I am using the new 1.18 version and in the config, I am setting so that it shows the mob health, but the GUI does not show it.
![image](https://user-images.githubusercontent.com/44974827/144764227-1b9b6775-8e77-4ffd-8b98-c9f48c2e5bca.png)

**Comment by mindforger** [comment] 2021-12-31 12:39
i can only +1 this issue and attach a forced crashlog ... hope this gets resolved soon, it annoys the F out of my gameplay to not be able to see health levels ... thing is it only happens for me using multiMC two other rplayers using curseforge do not have the problem as it seems! 
https://pastebin.com/LxhXWBK5

i crosstested it using different java versions (microsoft vs oracle) it seems to be related that i launch with multiMC 

if that is the case PLEASE fix it, since i do not want to create an overwolf account, i have enough accounts already

**Comment by McJty** [comment] 2021-12-31 14:41
I will check this

**Comment by McJty** [comment] 2021-12-31 15:11
I can reproduce the problem. Trying to figure out what's wrong

**Comment by McJty** [comment] 2021-12-31 15:39
Fixed in 5.0.2

**Closed as completed by McJty** 2021-12-31 15:39 UTC

**Comment by mindforger** [comment] 2021-12-31 17:47
Thx man, you are my hero of the year ;D
