### ISSUE TITLE
Reports ActuallyAdditions crops as their Seed versions (with seed images) instead of the plant version.

### ISSUE THREAD

**Issue by JaSpr** [McJty/TheOneProbe#128] opened 2017-02-06 06:30 UTC
Running "All The Mods" for 1.10.2.

http://i.imgur.com/lTqEAEb.jpg

Strangely (as the screenshot shows) WAILA gets it right, and WAILA is usually the one that's wrong.

**Comment by JaSpr** [comment] 2017-02-06 06:33
https://github.com/Ellpeck/ActuallyAdditions/issues/620

**Comment by Ellpeck** [comment] 2017-02-06 06:39
This can be closed as it's the intended behavior.

**Comment by JaSpr** [comment] 2017-02-06 06:48
Why would this be the intended behavior?

**Closed as completed** 2017-02-06 06:49 UTC
